# Generated by Django 3.2.4 on 2021-07-24 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='messageText',
        ),
    ]
